# Generated by Django 5.2.15 on 2026-06-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowstep',
            name='step_type',
            field=models.CharField(choices=[('extract_data', 'Extract Data'), ('create_record', 'Create Record'), ('send_email', 'Send Email'), ('generate_report', 'Generate Report'), ('http_request', 'HTTP Request')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='workflowstep',
            unique_together={('workflow', 'order')},
        ),
    ]
