# Generated by Django 5.2.15 on 2026-06-28 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_alter_workflowstep_step_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='false_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='false_branches', to='workflows.workflowstep'),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='true_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='true_branches', to='workflows.workflowstep'),
        ),
    ]
